[build]
  command = "npm install"

[build.environment]
  PORT = "6119"

[functions]
  directory = "functions/"

[[redirects]]
  from = "/translate"
  to = "/functions/index.js"
  status = 200

[[redirects]]
  from = "/"
  to = "/functions/index.js"
  status = 200
